---

env:
    browser: true

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:jsx-a11y/recommended

parser: babel-eslint

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        jsx: true
        modules: true

plugins:
    - react
    - jsx-a11y

settings:
    react:
        createClass: createReactClass
        pragma: React
        version: '16.0'
        flowVersion: '0.53'

    # The names of any functions used to wrap the propTypes object, e.g. `forbidExtraProps`.
    # If this isn't set, any propTypes wrapped in a function will be skipped.
    propWrapperFunctions:
        - forbidExtraProps

rules:
    semi: error


